# Generated by Django 3.0.6 on 2020-05-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_profile',
            new_name='author',
        ),
    ]
